# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=200)),
                ('urlToImage', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('source_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
