# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='publishedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
