# Generated by Django 2.0.6 on 2018-06-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=200)),
                ('urlToImage', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('publishedAt', models.DateField()),
            ],
            options={
                'db_table': 'info_news',
            },
        ),
    ]
