# Generated by Django 2.0.6 on 2018-06-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='publishedAt',
            field=models.DateTimeField(),
        ),
    ]
