# Generated by Django 2.0 on 2018-11-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='short_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
