# Generated by Django 2.0.6 on 2018-06-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180607_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='source_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
