# Generated by Django 2.0.6 on 2018-06-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_articles_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
