# Generated by Django 2.0 on 2018-11-11 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20181111_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='source_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category_Source'),
        ),
    ]
