# Generated by Django 2.0 on 2018-11-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20181111_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='source_category',
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(default='local', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='source_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
