# Generated by Django 2.0.6 on 2018-06-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180608_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='urlToImage',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
