# Generated by Django 2.0 on 2018-11-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20181111_0322'),
        ('news', '0006_auto_20181111_0503'),
    ]

    operations = [
    ]
