# Generated by Django 2.0 on 2018-11-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_merge_20181111_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markednews',
            name='news_id',
        ),
        migrations.RemoveField(
            model_name='markednews',
            name='username',
        ),
        migrations.DeleteModel(
            name='MarkedNews',
        ),
    ]
