# Generated by Django 2.0 on 2018-11-17 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0009_markednews'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcesSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category_Source')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-publishedAt']},
        ),
    ]
